### ISSUE TITLE
Error with plugging this package

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction-factories#2]
I'm trying to add this package to latest development reaction installation

```
+++ b/.meteor/packages
@@ -57,8 +57,9 @@ reactioncommerce:reaction-analytics-libs
 reactioncommerce:reaction-analytics
 reactioncommerce:reaction-social
 reactioncommerce:launchdock-connect
+reactioncommerce:reaction-factories
```

But I'v got errors in browser:

```
TypeError: undefined is not an object (evaluating 'faker.reaction = {}')
(anonymous function)reactioncommerce_reaction-factories.js:42836
(anonymous function)reactioncommerce_reaction-factories.js:43122
(anonymous function)orders.js:62

TypeError: undefined is not an object (evaluating 'Package['reactioncommerce:reaction-factories'].faker')
(anonymous function)global-imports.js:24
```

**Comment by newsiberian** [comment]
Hi, not need to add additional lines with `reactioncommerce:reaction-factories` to `.meteor/packages`. This dependency already contains in other `/packages/*/package.js`

**Comment by ramusus** [comment]
I didn't see any mention of `reactioncommerce:reaction-factories` in `.meteor/versions` file. I'm using recent development branch

**Comment by zenweasel** [comment]
@ramusus Hey Boris, are you still seeing this problem?

You won't see an entry in `versions` since the `package.js` files can require a particular version.

**Comment by ramusus** [comment]
@zenweasel yes. I still can not use Factory from the client:

```
> var shopId = faker.reaction.shops.getShop()._id;
< ReferenceError: Can't find variable: faker
> var shopId = Factory.get("Shops")
< ReferenceError: Can't find variable: Factory
```

And If I put `reactioncommerce:reaction-factories` into `.meteor/packages` I see error in console:

```
[Error] TypeError: undefined is not an object (evaluating 'faker.reaction = {}')
[Error] TypeError: undefined is not an object (evaluating 'Package['reactioncommerce:reaction-factories'].faker')
[Error] ReferenceError: Can't find variable: Template
[Error] ReferenceError: Can't find variable: Template
[Error] ReferenceError: Can't find variable: Template
[Error] ReferenceError: Can't find variable: Template
[Error] ReferenceError: Can't find variable: Template
[Error] ReferenceError: Can't find variable: Template
[Error] ReferenceError: Can't find variable: Template
[Error] ReferenceError: Can't find variable: Template
[Error] ReferenceError: Can't find variable: Template
[Error] ReferenceError: Can't find variable: Meteor
[Error] ReferenceError: Can't find variable: Router
```

I tried to change export to `api.export(["faker", "Factory"]);` in `packages/reaction-factories/package.js` but without visible success. Version of reaction-factories is 0.3.7

**Comment by zenweasel** [comment]
I don't believe faker is supposed to be available from the client.

**Comment by zenweasel** [comment]
@ramusus Nevermind, I see what you are saying. I will look at it.

**Comment by ramusus** [comment]
I think it would be handy to be able use factories from the client. When I start tests it works without errors about to factories, so my problem only about client.

**Comment by aaronjudd** [comment]
faker is available from the client now. let me know if that doesn't resolve this issue, and faker.reaction should work as well.
